// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSMS.Web.Data;

#nullable disable

namespace VSMS.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("VSMS.Web.Models.Application", b =>
                {
                    b.Property<Guid>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("VSMS.Web.Models.Opportunity", b =>
                {
                    b.Property<Guid>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxVolunteers")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("OpportunityId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("VSMS.Web.Models.OpportunitySkill", b =>
                {
                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinimumLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OpportunityId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("OpportunitySkills");
                });

            modelBuilder.Entity("VSMS.Web.Models.Organization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("VSMS.Web.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresCertification")
                        .HasColumnType("INTEGER");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("VSMS.Web.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VSMS.Web.Models.VolunteerSkill", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VolunteerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("VolunteerSkills");
                });

            modelBuilder.Entity("VSMS.Web.Models.Coordinator", b =>
                {
                    b.HasBaseType("VSMS.Web.Models.User");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Coordinators", (string)null);
                });

            modelBuilder.Entity("VSMS.Web.Models.Volunteer", b =>
                {
                    b.HasBaseType("VSMS.Web.Models.User");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalHours")
                        .HasColumnType("REAL");

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("VSMS.Web.Models.Application", b =>
                {
                    b.HasOne("VSMS.Web.Models.Opportunity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Web.Models.Volunteer", "Volunteer")
                        .WithMany("Applications")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Web.Models.Opportunity", b =>
                {
                    b.HasOne("VSMS.Web.Models.Organization", "Organization")
                        .WithMany("Opportunities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("VSMS.Web.Models.OpportunitySkill", b =>
                {
                    b.HasOne("VSMS.Web.Models.Opportunity", "Opportunity")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Web.Models.Skill", "Skill")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("VSMS.Web.Models.VolunteerSkill", b =>
                {
                    b.HasOne("VSMS.Web.Models.Skill", "Skill")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Web.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Web.Models.Coordinator", b =>
                {
                    b.HasOne("VSMS.Web.Models.Organization", "Organization")
                        .WithMany("Coordinators")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Web.Models.User", null)
                        .WithOne()
                        .HasForeignKey("VSMS.Web.Models.Coordinator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("VSMS.Web.Models.Volunteer", b =>
                {
                    b.HasOne("VSMS.Web.Models.User", null)
                        .WithOne()
                        .HasForeignKey("VSMS.Web.Models.Volunteer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSMS.Web.Models.Opportunity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("OpportunitySkills");
                });

            modelBuilder.Entity("VSMS.Web.Models.Organization", b =>
                {
                    b.Navigation("Coordinators");

                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("VSMS.Web.Models.Skill", b =>
                {
                    b.Navigation("OpportunitySkills");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("VSMS.Web.Models.Volunteer", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("VolunteerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
